### ISSUE TITLE
finir le déploiement auto sur netflify

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-frontend#1]
poster le lien vers l'application déployée sous Netlify

**Comment by PmRay** [comment]
https://romantic-cori-9bb7bb.netlify.com/

**Comment by Tilanchicha** [comment]
https://musing-liskov-ab226e.netlify.com/

**Comment by aminebousselmi** [comment]
Netlify : https://epic-mcnulty-dafb1e.netlify.com/

**Comment by HaoyunLIAO** [comment]
https://condescending-yalow-3d3277.netlify.com/

**Comment by ElomKossi** [comment]
https://sad-kepler-10830d.netlify.com/

**Comment by ajarno** [comment]
**App Netlify :** https://lp4a-pizza-project.netlify.com/

**Comment by EliasCh** [comment]
https://laughing-turing-994f43.netlify.com/

**Comment by bdaris** [comment]
https://determined-neumann-92aa34.netlify.com/

**Comment by GiovanniAffogbolo** [comment]
Deploy Netlify : https://reverent-mclean-eadb6f.netlify.com/

**Comment by EdwigeChristelle** [comment]
Lien vers App Netlifly: https://blissful-liskov-38bb75.netlify.com/

**Comment by nzodalandry** [comment]
https://mystifying-boyd-02c6ea.netlify.com/

**Comment by nzeneyannick** [comment]
Lien vers app.netlify : https://sharp-mclean-009f84.netlify.com/

**Comment by JINHOIGATE** [comment]
https://youthful-cray-de9aea.netlify.com/

**Comment by Emmanue8** [comment]
https://quizzical-poitras-3422cc.netlify.com/

**Comment by amina78** [comment]
https://competent-bhabha-8d875d.netlify.com/

**Comment by asaroukou** [comment]
https://gifted-austin-023690.netlify.com/

**Comment by chensy317** [comment]
https://inspiring-bohr-9e1a8e.netlify.com/

**Comment by stanicchris** [comment]
https://pizzalp4a.netlify.com

**Comment by lordkevinmo** [comment]
https://shopizza.netlify.com/

**Comment by larissakouete** [comment]
https://hungry-goldstine-3844f0.netlify.com/

**Comment by sola3HH** [comment]
https://wonderful-bohr-418d24.netlify.com/

**Comment by UTSam** [comment]
flamboyant-hugle-343f22.netlify.com

**Comment by ThibautRousselet** [comment]
https://lp4athibautrousselet.netlify.com/

**Comment by LPA2-Automne2016** [comment]
OK
