### ISSUE TITLE
mettre en place la page de détails de la pizza

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/projet-frontend#2]
à partir du tutorial angular ici 
https://angular.io/tutorial/toh-pt5

mettre en place le routage sur notre application
pour que lorsqu'on clique sur une pizza la page de détail de la pizza s'affiche

créer le composant de détail de  la pizza
créer la méthode du service pizza pour récupérer ce détail
mettre en place le routage angular et créer les deux routes 

une pour la liste des pizzas et une pour le détail

**Comment by GiovanniAffogbolo** [comment]
AFFOGBOLO Giovanni
 **1)** Lien Netlify liste des pizzas : https://dazzling-williams-f5c883.netlify.com/
 **2)** Lien Netlify affichage details d'une pizza : https://dazzling-williams-f5c883.netlify.com/pizzas/1

**Comment by EliasCh** [comment]
* https://laughing-turing-994f43.netlify.com/

**Comment by lordkevinmo** [comment]
https://shopizza.netlify.com/

**Comment by stanicchris** [comment]
https://pizzalp4a.netlify.com

**Comment by aminebousselmi** [comment]
https://epic-mcnulty-dafb1e.netlify.com/pizza

**Comment by nzodalandry** [comment]
https://gespizza.netlify.com

**Comment by EdwigeChristelle** [comment]
Lien vers les pizzas: https://shoppizzaedwige.netlify.com

**Comment by larissakouete** [comment]
https://hungry-goldstine-3844f0.netlify.com

**Comment by amina78** [comment]
https://competent-bhabha-8d875d.netlify.com

**Comment by chensy317** [comment]
https://inspiring-bohr-9e1a8e.netlify.com

**Comment by ElomKossi** [comment]
https://sad-kepler-10830d.netlify.com

**Comment by Tilanchicha** [comment]
Lien vers pizza: https://musing-liskov-ab226e.netlify.com/pizza

**Comment by Tilanchicha** [comment]
Lien qui marche ^^: https://musing-liskov-ab226e.netlify.com

**Comment by ajarno** [comment]
**Lien Netlify :** https://lp4a-pizza-project.netlify.com

**Comment by HaoyunLIAO** [comment]
Lien : https://pizzashy.netlify.com/pizza-list

**Comment by nzeneyannick** [comment]
https://sharp-mclean-009f84.netlify.com

**Comment by EleryanYuri** [comment]
**Lien Netlifly : ** https://lp4apizza.netlify.com/

**Comment by sola3HH** [comment]
https://wonderful-bohr-418d24.netlify.com/pizza-list

**Comment by asaroukou** [comment]
https://gifted-austin-023690.netlify.com/

**Comment by UTSam** [comment]
https://flamboyant-hugle-343f22.netlify.com/pizza

**Comment by ThibautRousselet** [comment]
https://lp4athibautrousselet.netlify.com/pizzas

**Comment by JINHOIGATE** [comment]
https://youthful-cray-de9aea.netlify.com/pizzas/1

**Comment by LPA2-Automne2016** [comment]
Bon boulot à tous,
mention spéciale à @asaroukou, joli boulot, c'est propre, presque de qualité professionnelle.
